{
 "title": "FastAPI + Redis Monitoring",
 "tags": [
  "Production",
  "FastAPI",
  "Redis"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "QPS per Endpoint",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "sum(rate(request_count_total[1m])) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Latency P95 per Endpoint",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_latency_seconds_bucket[1m])) by (le, endpoint))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Error Rate %",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "sum(rate(error_count_total[1m])) / sum(rate(request_count_total[1m])) * 100",
     "legendFormat": "Error Rate %"
    }
   ]
  },
  {
   "title": "Redis Memory Used",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 6, "w": 12, "h": 6 },
   "targets": [
    { "expr": "redis_memory_used_bytes", "legendFormat": "Redis Memory" }
   ]
  },
  {
   "title": "Redis Connected Clients",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 12, "w": 12, "h": 6 },
   "targets": [
    { "expr": "redis_connected_clients", "legendFormat": "Redis Connections" }
   ]
  }
 ]
}